# Generated by Django 6.0 on 2025-12-11 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ogloszenia', '0002_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
