# Generated by Django 6.0 on 2025-12-18 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ogloszenia', '0002_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
