# Generated by Django 6.0 on 2025-12-26 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ogloszenia', '0004_article_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='category',
        ),
        migrations.AddField(
            model_name='article',
            name='categories',
            field=models.ManyToManyField(related_name='articles', to='ogloszenia.category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
