# Generated by Django 5.2.10 on 2026-02-04 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_logentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapedPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('title', models.CharField(max_length=255)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
