"""utworzenie tabeli zadan

Revision ID: 35eb1576dd0e
Revises: 
Create Date: 2025-11-17 17:59:00.575097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35eb1576dd0e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zadania',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('opis', sa.String(), nullable=False),
    sa.Column('zrobione', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('zadania')
    # ### end Alembic commands ###
